language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: ['kalakris-cmake', 'ubuntu-toolchain-r-test', 'boost-latest']
          packages: ['python-pip', 'g++-4.9', 'cmake', 'libhwloc-dev', 'libboost1.55-all-dev']
      before_script:
        - pip install --user git+git://github.com/eddyxu/cpp-coveralls.git
      after_success:
        - make test
        - coveralls -i src -i xi --gcov-options '\lp' --gcov 'gcov-4.9'
      env: COMPILER=g++-4.9
    - os: linux
      addons:
        apt:
          sources: ['kalakris-cmake', 'boost-latest', 'llvm-toolchain-precise']
          packages: ['llvm-3.8', 'llvm-3.8-dev', 'cmake', 'libhwloc-dev', 'libboost1.55-all-dev']
      after_success:
        - make test
      env: COMPILER=clang++-3.8

script:
  - CXX=$COMPILER cmake . -DHWLOC=ON -DNUMA=OFF -DCMAKE_BUILD_TYPE=Debug
  - make

