language: cpp
compiler:
  - clang
  - gcc

script: cmake . && make && make test

os: linux

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libjemalloc-dev libboost-all-dev libevent-dev
