language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: ['kalakris-cmake', 'ubuntu-toolchain-r-test', 'boost-latest']
          packages: ['python-pip', 'g++-4.9', 'cmake', 'libhwloc-dev', 'libboost1.55-all-dev']
      before_script:
        - pip install --user git+git://github.com/eddyxu/cpp-coveralls.git
      after_success:
        - make test
        - coveralls -i src -i xi --gcov-options '\lp' --gcov 'gcov-4.9'
      env: COMPILER=g++-4.9
    - os: linux
      addons:
        apt:
          sources: ['kalakris-cmake', 'ubuntu-toolchain-r-test', 'boost-latest']
          packages: ['g++-5', 'cmake', 'libhwloc-dev', 'libboost1.55-all-dev']
      after_success:
        - make test
      env: COMPILER=g++-5
    - os: linux
      addons:
        apt:
          sources: ['kalakris-cmake', 'boost-latest', 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
          packages: ['clang-3.8', 'cmake', 'libhwloc-dev', 'libstdc++-4.9-dev','libboost1.55-all-dev']
      after_success:
        - make test
      env: COMPILER=clang++-3.8

script:
  - CXX=$COMPILER cmake . -DHWLOC=ON -DNUMA=OFF -DEMULATE_MADVISE=ON -DCMAKE_BUILD_TYPE=Debug
  - make

