language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: ['kalakris-cmake', 'ubuntu-toolchain-r-test', 'boost-latest']
          packages: ['python-pip', 'g++-4.9', 'cmake', 'libhwloc-dev', 'libboost1.58-all-dev']
      before_script:
        - pip install --user git+git://github.com/eddyxu/cpp-coveralls.git
      after_success:
        - make test
        - coveralls -i src -i xi --gcov-options '\lp' --gcov 'gcov-4.9'
      env: COMPILER=g++-4.9

script:
  - CXX=$COMPILER cmake . -DHWLOC=ON -DCMAKE_BUILD_TYPE=Debug -DEVENT__DISABLE_TESTS=ON
  - make

