language: cpp
compiler:
  #- clang
  - gcc

script: cmake . && make && make test

os: linux

before_install:
  - sudo apt-get install -y python-software-properties
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - sudo apt-get install -y libjemalloc-dev libboost1.55-dev libboost-thread1.55-dev libboost-timer1.55-dev libevent-dev
