language: cpp
compiler:
  - clang
  - gcc

script: cmake . && make && make test

os: linux

before_install:
  - sudo apt-get install -y python-software-properties
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y libjemalloc-dev libboost1.55-dev libboost-thread1.55-dev libboost-timer1.55-dev libevent-dev
